export type P2Event = {
  id: number;
  name: string;
  summary: string;
  description: string;
  date: string;
  time: string;
  startTime: number;
  endTime: number;
  location: string;
  price: number;
  capacity: number;
  registered: number;
  organizer: `0x${string}`;
  imageURI: string;
  tone: "blue" | "violet" | "amber" | "green";
  tags: string[];
  rating: number;
  cancelled?: boolean;
  settled?: boolean;
};
